### ISSUE TITLE
ValueError: Namespace Libinsane not available on start

### ISSUE THREAD

**Issue by BonaBeavis** [paperwork/paperwork#925]
**Describe the bug**
Start fail with:

```
Traceback (most recent call last):
  File "/usr/bin/paperwork", line 11, in <module>
    load_entry_point('paperwork==1.3.0', 'gui_scripts', 'paperwork')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/paperwork/paperwork.py", line 54, in <module>
    gi.require_version('Libinsane', '1.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Libinsane not available
```

This is confirmed:
```
paperwork-shell chkdeps paperwork       
Detected system: ubuntu 19.10 Eoan Ermine
/usr/lib/python3/dist-packages/paperwork/deps.py:142: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  __import__(module[1])


WARNING: Missing dependencies:
  - Libinsane (scanner support) (python module: gi.repository.Libinsane)
```

But:
```
sudo apt-get install libsane 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libsane is already the newest version (1.0.27-3.2ubuntu3).
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10

**Comment by jflesch** [comment]
Wrong project. The one you're looking for is here: https://gitlab.gnome.org/World/OpenPaperwork/paperwork/
And the up-to-date documentation you're looking for:  https://gitlab.gnome.org/World/OpenPaperwork/paperwork/blob/master/doc/install.debian.markdown

**Comment by yowilfre82** [comment]
> Wrong project. The one you're looking for is here: https://gitlab.gnome.org/World/OpenPaperwork/paperwork/
> And the up-to-date documentation you're looking for: https://gitlab.gnome.org/World/OpenPaperwork/paperwork/blob/master/doc/install.debian.markdown

i fallow this steps , but the result is the same, im still getting the error
