### ISSUE TITLE
ValueError: Namespace Libinsane not available

### ISSUE THREAD

**Issue by yowilfre82** [paperwork/paperwork#931]
**Describe the bug**
 when run paperwork command

Traceback (most recent call last):
  File "/usr/local/bin/paperwork", line 5, in <module>
    from paperwork.paperwork import main
  File "/usr/local/lib/python3.6/dist-packages/paperwork/paperwork.py", line 54, in <module>
    gi.require_version('Libinsane', '1.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Libinsane not available

**Desktop (please complete the following information):**
 - OS: Linux Mint 19

I falow this https://github.com/paperwork/paperwork/issues/925#issuecomment-557440572 , but the result is the same, im still getting the error

**Comment by mrusme** [comment]
This is the wrong project. You're looking for https://gitlab.gnome.org/World/OpenPaperwork/paperwork.
